AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
]

app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.home, name='home'),
    url(r'^home/$',views.home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$',views.market, name='market'),
    url(r'^cart/$',views.cart, name='cart'),
    url(r'^mine/$',views.mine, name='mine'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^quit/$', views.quit, name='quit'),
    url(r'^checkuser/$', views.checkuser, name='checkuser')
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block extcss%}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block title %}
    <title>登录界面</title>
{% endblock %}


{% block content %}
     <div class="login">
         <div class="back">
             <a href="{% url 'axf:mine' %}">
                 <span class="glyphicon  glyphicon-remove"></span>
             </a>
         </div>
         <form action="{% url 'axf:login' %}" method="post"
         enctype="multipart/form-data">
             {% csrf_token %}
             <div class="input-group">
                 <span class="input-group-addon" id="basic-addon1">账号</span>
                 <input  type="text" class="form-control" placeholder="用户名/手机号" aria-describedby="basic-addon1" name="account">

             </div>

             <div class="input-group">
                 <span class="input-group-addon" id="basic-addon1">密码</span>
                <input type="password" class="form-control" placeholder="6位数的密码" aria-describedby="basic-addon1" name="password">
             </div>
             {% if error %}
                 <p class="err">{{ error }}</p>
             {% endif %}

              <div class="input-group">
                  <span></span>

             </div>

             <div class="login-wrapper">
               <input class="btn btn-primary" value="登录" id="subButton" type="submit">

             </div>
         </form>
     </div>
{% endblock %}









{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}



{% block title %}
    <title>我的</title>
{% endblock %}


{% block content %}
        <div class="mine">
           <div class="user-wrapper ">
               <div class="user-img">
                   <img src="{{ img }}" alt="">
               </div>

               <div class="user-content">
                   <p><a href="{% url 'axf:login' %}"><span class="glyphicon glyphicon-user"></span>{{ name }}</a> </p>
                   <p><span class="glyphicon glyphicon-flash"></span>VIP:{{ rank }} </p>
                   <a href="{% url 'axf:register' %}" class="register">注册</a>
               </div>

           </div>

           <div class="collect">
                <b class="glyphicon glyphicon-heart"></b>
                <span>收藏</span>
           </div>

           <div class="other">
               <section class="my">
                       <span>我的订单</span>
                       <a href="#">查看全部订单<b class="glyphicon glyphicon-chevron-right"></b> </a>
               </section>

               <section>
                    <ul>
                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-usd"></d></dt>
                                    <dd>代付款</dd>
                                </dl>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-leaf"></d></dt>
                                    <dd>待收货</dd>
                                </dl>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-fire"></d></dt>
                                    <dd>待评价</dd>
                                </dl>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-magnet"></d></dt>
                                    <dd>退款/售后</dd>
                                </dl>
                            </a>
                        </li>
                    </ul>
               </section>


               <section>
                    <ul>
                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-usd"></d></dt>
                                    <dd>优惠卷</dd>
                                </dl>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-leaf"></d></dt>
                                    <dd>收货地址</dd>
                                </dl>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-fire"></d></dt>
                                    <dd>客服/反馈</dd>
                                </dl>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <dl>
                                    <dt><d class="glyphicon glyphicon-magnet"></d></dt>
                                    <dd>关于我们</dd>
                                </dl>
                            </a>
                        </li>
                    </ul>
               </section>

               {% if islogin %}
                   <section class="quit">

                       <a href="{% url 'axf:quit' %}">退出登录</a>

                   </section>
               {% endif %}
           </div>

        </div>

{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <title>注册界面</title>
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}



{%  block content %}
    <div class="register">
         <div class="back"><a href="{% url 'axf:mine' %}">
             <span class=" glyphicon glyphicon-remove ">
             </span> </a>
         </div>

        <form action="{% url 'axf:register' %}"
              method="post" enctype="multipart/form-data">
            {% csrf_token %}
             <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">账号</span>
                <input id="account" type="text" class="form-control" placeholder="账号" aria-describedby="basic-addon1" name="account">
             </div>
             <span class="error" id="accounterr">用户名存在</span>

             <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">密码</span>
                <input id="password" type="password" class="form-control" placeholder="密码长度6~12位数" aria-describedby="basic-addon1" name="password">
             </div>
             <span class="error" id="pasworderr">密码不合法</span>

             <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">验证</span>
                <input id="mypassword" type="password" class="form-control" placeholder="密码长度6~12位数" aria-describedby="basic-addon1" name="mypassword">
             </div>
             <span class="error" id="mypassworderr">验证密码不正确</span>

             <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">昵称</span>
                <input id="account" type="text" class="form-control" placeholder="" aria-describedby="basic-addon1" name="name">
             </div>

             <div class="input-group tel-view">
                <span class="input-group-addon" id="basic-addon1">电话</span>
                <input id="tel" type="text" class="form-control" placeholder="" aria-describedby="basic-addon1" name="tel">
                 <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
             </div>


             <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">地址</span>
                <input id="address" type="text" class="form-control" placeholder="" aria-describedby="basic-addon1" name="address">
             </div>

             <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">头像</span>
                <input  type="file" name="file" >
              </div>


             <input class="btn btn-primary" value="注册" id="subButton" type="submit">
        </form>
    </div>
{% endblock %}








{% block extjs %}
    <script src="{% static 'mine/js/register.js' %}"></script>
{% endblock %}